name: Build RitimPlayer APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Extract Ritim project
        run: |
          mkdir -p buildsrc
          unzip -q Ritim-Android-Pla* -d buildsrc

      - name: Find and Build APK
        run: |
          # gradlew dosyasının olduğu yeri bulup oraya geçiyoruz
          GRADLE_DIR=$(find buildsrc -name "gradlew" -exec dirname {} \;)
          echo "Gradle klasörü: $GRADLE_DIR"
          cd "$GRADLE_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RitimPlayer-APK
          path: /**/*.apk
          
